package reports

import (
	"errors"

	"github.com/chrisostomemataba/balceinv-api/internal/documents"
)

const (
	ReportSummary   = "summary"
	ReportDaily     = "daily"
	ReportProducts  = "products"
	ReportCashiers  = "cashiers"
	ReportShops     = "shops"
	ReportInventory = "inventory"
	ReportDeadStock = "dead-stock"
)

var ErrUnknownReport = errors.New("choose summary, daily, products, cashiers, shops, inventory or dead-stock")

type ExportRequest struct {
	Report   string
	Format   string
	Language string
	Sort     string
	Range    RangeRequest
}

type exportContext struct {
	branding documents.Branding
	language string
	scope    Scope
}

var exportLabels = map[string]map[string]string{
	documents.English: {
		"title.summary":     "Sales report",
		"title.daily":       "Sales per day",
		"title.products":    "Products sold",
		"title.cashiers":    "Sales per staff member",
		"title.shops":       "Sales per shop",
		"title.inventory":   "Stock on hand",
		"sheet.days":        "Days",
		"sheet.products":    "Products",
		"sheet.staff":       "Staff",
		"sheet.shops":       "Shops",
		"sheet.stock":       "Not selling",
		"date":              "Date",
		"sales":             "Sales",
		"takings":           "Takings",
		"takingsInclTax":    "Takings (incl. tax)",
		"tax":               "Tax",
		"netSales":          "Net sales",
		"cost":              "Cost",
		"costOfGoods":       "Cost of goods",
		"grossProfit":       "Gross profit",
		"margin":            "Margin",
		"product":           "Product",
		"sku":               "SKU",
		"quantity":          "Quantity",
		"itemsSold":         "Items sold",
		"staff":             "Staff",
		"averageSale":       "Average sale",
		"shop":              "Shop",
		"shops":             "Shops",
		"allShops":          "All shops",
		"discountsGiven":    "Discounts given",
		"cash":              "Cash",
		"card":              "Card",
		"mobileMoney":       "Mobile money",
		"onHand":            "On hand",
		"valueAtCost":       "Value at cost",
		"lastSold":          "Last sold",
		"neverSold":         "Never sold",
		"stockValueCost":    "Stock value at cost",
		"stockValuePrice":   "Stock value at price",
		"productsInStock":   "Products",
		"unitsInStock":      "Items on hand",
		"runningLow":        "Running low",
		"outOfStock":        "Out of stock",
		"rankedBy":          "Ranked by",
		"sort.revenue":      "Sales",
		"sort.quantity":     "Quantity",
		"sort.profit":       "Profit",
		"notSoldFor":        "Not sold for (days)",
		"stockAsAt":         "Stock as at {date}",
		"period":            "Period",
		"title.dead-stock":  "Stock not selling",
		"sumTakings":        "Takings",
		"sumTakingsInclVat": "Takings, including VAT",
		"sumLessVat":        "Less: VAT",
		"sumNetSales":       "Net sales",
		"sumLessCost":       "Less: cost of goods sold",
		"sumGrossProfit":    "Gross profit",
		"sumGrossLoss":      "Gross loss",
		"sumGrossMargin":    "Gross margin",
		"sumPaid":           "How customers paid",
		"payLater":          "Pay later (on credit)",
		"sumTotalPaid":      "Total paid",
		"sumOther":          "Other figures",
		"sumDiscounts":      "Discounts given (already taken off takings)",
		"sumNoteTakings":    "Takings are what customers paid after discounts, including VAT where it was charged.",
		"sumNoteCost":       "Cost of goods uses each product's buying cost on the day it was sold.",
		"sumNoteCredit":     "Pay later is sold on credit and is still owed until the customer pays.",
		"comparedWith":      "Compared with",
		"total":             "Total",
		"vat":               "VAT",
		"category":          "Category",
		"status":            "Status",
		"costPrice":         "Buying price",
		"sellingPrice":      "Selling price",
		"valueAtPrice":      "Value at selling price",
		"stockNote":         "Values use each product's current buying and selling prices.",
		"deadValueNote":     "Values use each product's current buying price.",
		"deadNote":          "Products with stock that have not sold in the last {days} days, with the most money tied up first. Change the number of days in Settings.",
		"deadCount":         "Products not selling",
		"dailyNote":         "Days without sales are shown so gaps are easy to see.",
		"productsNote":      "Ranked by {sort}. Net sales leave out VAT; margin is gross profit as a share of net sales.",
		"staffNote":         "Takings include VAT; each sale counts for the staff member who served it.",
		"shopsNote":         "Takings include VAT; cost of goods uses each product's buying cost on the day it was sold.",
		"emptySales":        "No sales in this period",
		"emptyStock":        "No products yet",
		"emptyDead":         "Every product with stock has sold recently",
	},
	documents.Swahili: {
		"title.summary":     "Ripoti ya mauzo",
		"title.daily":       "Mauzo kwa siku",
		"title.products":    "Bidhaa zilizouzwa",
		"title.cashiers":    "Mauzo kwa mfanyakazi",
		"title.shops":       "Mauzo kwa duka",
		"title.inventory":   "Stoku iliyopo",
		"sheet.days":        "Siku",
		"sheet.products":    "Bidhaa",
		"sheet.staff":       "Wafanyakazi",
		"sheet.shops":       "Maduka",
		"sheet.stock":       "Bidhaa zisizouzwa",
		"date":              "Tarehe",
		"sales":             "Mauzo",
		"takings":           "Makusanyo",
		"takingsInclTax":    "Makusanyo (pamoja na kodi)",
		"tax":               "Kodi",
		"netSales":          "Mauzo halisi",
		"cost":              "Gharama",
		"costOfGoods":       "Gharama ya bidhaa",
		"grossProfit":       "Faida ghafi",
		"margin":            "Asilimia ya faida",
		"product":           "Bidhaa",
		"sku":               "SKU",
		"quantity":          "Idadi",
		"itemsSold":         "Vipande vilivyouzwa",
		"staff":             "Mfanyakazi",
		"averageSale":       "Wastani wa mauzo",
		"shop":              "Duka",
		"shops":             "Maduka",
		"allShops":          "Maduka yote",
		"discountsGiven":    "Punguzo lililotolewa",
		"cash":              "Taslimu",
		"card":              "Kadi",
		"mobileMoney":       "Pesa ya simu",
		"onHand":            "Zilizopo",
		"valueAtCost":       "Thamani kwa bei ya kununua",
		"lastSold":          "Iliuzwa mwisho",
		"neverSold":         "Haijawahi kuuzwa",
		"stockValueCost":    "Thamani ya stoku kwa bei ya kununua",
		"stockValuePrice":   "Thamani ya stoku kwa bei ya kuuza",
		"productsInStock":   "Bidhaa",
		"unitsInStock":      "Vipande vilivyopo",
		"runningLow":        "Stoku ndogo",
		"outOfStock":        "Zimeisha",
		"rankedBy":          "Zimepangwa kwa",
		"sort.revenue":      "Mauzo",
		"sort.quantity":     "Idadi",
		"sort.profit":       "Faida",
		"notSoldFor":        "Hazijauzwa kwa (siku)",
		"stockAsAt":         "Stoku kufikia {date}",
		"period":            "Kipindi",
		"title.dead-stock":  "Stoku isiyouzwa",
		"sumTakings":        "Makusanyo",
		"sumTakingsInclVat": "Makusanyo, pamoja na VAT",
		"sumLessVat":        "Toa: VAT",
		"sumNetSales":       "Mauzo halisi",
		"sumLessCost":       "Toa: gharama ya bidhaa zilizouzwa",
		"sumGrossProfit":    "Faida ghafi",
		"sumGrossLoss":      "Hasara ghafi",
		"sumGrossMargin":    "Asilimia ya faida ghafi",
		"sumPaid":           "Jinsi wateja walivyolipa",
		"payLater":          "Lipa baadaye (mkopo)",
		"sumTotalPaid":      "Jumla iliyolipwa",
		"sumOther":          "Takwimu nyingine",
		"sumDiscounts":      "Punguzo lililotolewa (tayari limetolewa kwenye makusanyo)",
		"sumNoteTakings":    "Makusanyo ni kiasi walicholipa wateja baada ya punguzo, pamoja na VAT pale ilipotozwa.",
		"sumNoteCost":       "Gharama ya bidhaa inatumia bei ya kununua ya kila bidhaa siku ilipouzwa.",
		"sumNoteCredit":     "Lipa baadaye ni mauzo ya mkopo na bado yanadaiwa hadi mteja alipe.",
		"comparedWith":      "Ikilinganishwa na",
		"total":             "Jumla",
		"vat":               "VAT",
		"category":          "Kundi",
		"status":            "Hali",
		"costPrice":         "Bei ya kununua",
		"sellingPrice":      "Bei ya kuuza",
		"valueAtPrice":      "Thamani kwa bei ya kuuza",
		"stockNote":         "Thamani zinatumia bei ya sasa ya kununua na kuuza ya kila bidhaa.",
		"deadValueNote":     "Thamani zinatumia bei ya sasa ya kununua ya kila bidhaa.",
		"deadNote":          "Bidhaa zenye stoku ambazo hazijauzwa kwa siku {days} zilizopita, zenye pesa nyingi zaidi kwanza. Badilisha idadi ya siku kwenye Mipangilio.",
		"deadCount":         "Bidhaa zisizouzwa",
		"dailyNote":         "Siku zisizo na mauzo zimeonyeshwa ili mapengo yaonekane kwa urahisi.",
		"productsNote":      "Zimepangwa kwa {sort}. Mauzo halisi hayahusishi VAT; asilimia ni faida ghafi ikilinganishwa na mauzo halisi.",
		"staffNote":         "Makusanyo yanajumuisha VAT; kila mauzo yanahesabiwa kwa mfanyakazi aliyehudumia.",
		"shopsNote":         "Makusanyo yanajumuisha VAT; gharama ya bidhaa inatumia bei ya kununua ya kila bidhaa siku ilipouzwa.",
		"emptySales":        "Hakuna mauzo katika kipindi hiki",
		"emptyStock":        "Bado hakuna bidhaa",
		"emptyDead":         "Kila bidhaa yenye stoku imeuzwa hivi karibuni",
	},
}
