package documents

import (
	"strings"
	"time"
)

var labelsByLanguage = map[string]map[string]string{
	English: {
		"tin":           "TIN",
		"vrn":           "VRN",
		"total":         "Total",
		"summary":       "Summary",
		"item":          "Item",
		"value":         "Value",
		"filters":       "Filters",
		"filter":        "Filter",
		"number":        "No.",
		"generatedBy":   "Generated by {user} on {date}",
		"pdfFooter":     "Page {current} of {total} · Generated by Balce on {date} by {user}",
		"excelFooter":   "Page &P of &N",
		"nothingToShow": "Nothing to show",

		"statementChange":     "Change",
		"statementCode":       "Code",
		"statementContinued":  "(continued)",
		"statementAmountsIn":  "Amounts in {currency}",
		"statementNotes":      "Notes",
		"statementPreparedBy": "Prepared by",
		"statementCheckedBy":  "Checked and approved by",
		"statementDate":       "Date",
	},
	Swahili: {
		"tin":           "TIN",
		"vrn":           "VRN",
		"total":         "Jumla",
		"summary":       "Muhtasari",
		"item":          "Kipengele",
		"value":         "Thamani",
		"filters":       "Vichujio",
		"filter":        "Kichujio",
		"number":        "Na.",
		"generatedBy":   "Imetolewa na {user} tarehe {date}",
		"pdfFooter":     "Ukurasa {current} kati ya {total} · Imetolewa na Balce tarehe {date} na {user}",
		"excelFooter":   "Ukurasa &P kati ya &N",
		"nothingToShow": "Hakuna cha kuonyesha",

		"statementChange":     "Mabadiliko",
		"statementCode":       "Namba",
		"statementContinued":  "(inaendelea)",
		"statementAmountsIn":  "Kiasi kwa {currency}",
		"statementNotes":      "Maelezo",
		"statementPreparedBy": "Imeandaliwa na",
		"statementCheckedBy":  "Imekaguliwa na kuidhinishwa na",
		"statementDate":       "Tarehe",
	},
}

var monthNamesByLanguage = map[string][12]string{
	English: {"Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"},
	Swahili: {"Jan", "Feb", "Mac", "Apr", "Mei", "Jun", "Jul", "Ago", "Sep", "Okt", "Nov", "Des"},
}

func Label(language string, key string, replacements ...string) string {
	labelText, isKnown := labelsByLanguage[ResolveLanguage(language)][key]
	if !isKnown {
		labelText = labelsByLanguage[English][key]
	}
	return strings.NewReplacer(replacements...).Replace(labelText)
}

func MonthYear(language string, moment time.Time) string {
	return monthName(language, moment.Month()) + " " + moment.Format("2006")
}

func monthName(language string, month time.Month) string {
	return monthNamesByLanguage[ResolveLanguage(language)][month-1]
}
