DROP POLICY tenant_isolation ON suppliers;
ALTER TABLE suppliers NO FORCE ROW LEVEL SECURITY;
ALTER TABLE suppliers DISABLE ROW LEVEL SECURITY;
DROP POLICY tenant_isolation ON supplier_document_counters;
ALTER TABLE supplier_document_counters NO FORCE ROW LEVEL SECURITY;
ALTER TABLE supplier_document_counters DISABLE ROW LEVEL SECURITY;
DROP POLICY tenant_isolation ON purchase_orders;
ALTER TABLE purchase_orders NO FORCE ROW LEVEL SECURITY;
ALTER TABLE purchase_orders DISABLE ROW LEVEL SECURITY;
DROP POLICY tenant_isolation ON purchase_order_lines;
ALTER TABLE purchase_order_lines NO FORCE ROW LEVEL SECURITY;
ALTER TABLE purchase_order_lines DISABLE ROW LEVEL SECURITY;
DROP POLICY tenant_isolation ON purchases;
ALTER TABLE purchases NO FORCE ROW LEVEL SECURITY;
ALTER TABLE purchases DISABLE ROW LEVEL SECURITY;
DROP POLICY tenant_isolation ON purchase_lines;
ALTER TABLE purchase_lines NO FORCE ROW LEVEL SECURITY;
ALTER TABLE purchase_lines DISABLE ROW LEVEL SECURITY;
DROP POLICY tenant_isolation ON supplier_payments;
ALTER TABLE supplier_payments NO FORCE ROW LEVEL SECURITY;
ALTER TABLE supplier_payments DISABLE ROW LEVEL SECURITY;
DROP POLICY tenant_isolation ON supplier_returns;
ALTER TABLE supplier_returns NO FORCE ROW LEVEL SECURITY;
ALTER TABLE supplier_returns DISABLE ROW LEVEL SECURITY;
DROP POLICY tenant_isolation ON supplier_return_lines;
ALTER TABLE supplier_return_lines NO FORCE ROW LEVEL SECURITY;
ALTER TABLE supplier_return_lines DISABLE ROW LEVEL SECURITY;
